- name: Set vars
  set_fact:
    app_type: "{{ app_dir | dirname | basename }}"

- name: Read kubify.yml
  include_vars:
    file: "{{ kubify_yml }}"
    name: kubify_config

- name: Read application port
  set_fact:
    app_port: "{{ kubify_config | json_query('service.port') | default(8080, true) }}"

    # TODO(Phil9000): add more checks to support more languages 
- name: Check if requirements.txt exists
  stat:
    path: "{{ app_dir}}/requirements.txt"
  register: requirements_txt_file

- name: Check if pom.xml exists
  stat:
    path: "{{ app_dir}}/pom.xml"
  register: pom_xml_file

- name: Check if csproj exists
  stat:
    path: "{{ app_dir}}/app.csproj"
  register: csproj_file

- name: Check if package.json exists
  stat:
    path: "{{ app_dir}}/package.json"
  register: package_json_file

- name: Check if yarn.lock exists
  stat:
    path: "{{ app_dir}}/yarn.lock"
  register: yarn_lock_file

- name: Read package.json
  include_vars:
    file: "{{ app_dir }}/package.json"
    name: package_json
  when: package_json_file.stat.exists

- name: Read app version
  set_fact:
    app_cicd_build_image_version: "{{ package_json | json_query('version') }}"

- name: Read node engine version
  set_fact:
    package_json_node_version: "{{ package_json | json_query('engines.node') | default('10.15.1', true) }}"

- name: Create kubify work directory
  file:
    path: "{{ app_kubify_dir }}"
    state: directory

- name: Create kubify work manifests directory
  file:
    path: "{{ app_kubify_dir }}/manifests"
    state: directory

- name: Read profile config
  include_vars:
    file: "{{ app_dir }}/config/config.{{ profile }}.yaml"
    name: profile_config